M48
; DRILL file {KiCad 8.0.2} date 2024-07-15T20:50:25+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-15T20:50:25+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.4993Y-4.7617
X6.7268Y-4.7617
T2
X7.0141Y-3.9619
X7.0141Y-4.2769
M30
